### ISSUE TITLE
Benchmark differences

### ISSUE THREAD

**Issue by drasko** [rs/zerolog#236]
Benchamrks published [here](https://github.com/rs/zerolog#benchmarks) differ from Uber's benchmarks published [here](https://github.com/uber-go/zap#performance).

In their benchmark Zap seems to have better performance for "Log a message and 10 fields" case.

Why is that?

**Comment by rs** [comment]
They use `Interface` instead of `Ints`, `Strings`, `Array` etc with our library and use the proper function on theirs. `Interface` is using reflection, it's the worse method you can call on our lib. The comparison isn't fair.

See my comment in the PR when they introduced it: https://github.com/uber-go/zap/pull/483#issuecomment-317766488
