### ISSUE TITLE
How to read Event in a Hook?

### ISSUE THREAD

**Issue by goteppo** [rs/zerolog#300]
Hi.

I'm not sure if I missed something obvious, but is there a way to read what data (key-value pairs) have been added to an Event, given that the Event fields are not exported?

With logrus I had used a hook to send certain log details to a db, which was trivial to implement when the logrus event (called Entry) has exported fields that can be read from the hook (specifically the Data field that contains a map of all the key-value pairs).

Is the same possible using zerolog?

Thanks.

**Comment by rs** [comment]
You can't access the fields because they are written to the JSON serialized byte buffer right away to avoid allocation and safe CPU.

**Comment by goteppo** [comment]
Thank you for confirming. That makes sense.

**Comment by Vanclief** [comment]
Looking for the same functionality, only thing I am missing from this awesome library.

@rs I have no idea where the byte buffer is, but could't it be possible to access the  buffer and manually unmarshall the JSON fields?

**Comment by Vanclief** [comment]
Taking a quick look at the code, would it be viable to add a simple get to `event.go` such as:

event.go
```
func (e *Event) Buf() []byte {
	return e.buf
}
```

So that you could
```

log.Info().Object("obj", nil).Str("foo", "bar").Int("age", 10)

...

func (h SeverityHook) Run(e *zerolog.Event, level zerolog.Level, msg string) {
   buf := e.Buf() 
   fmt.Println(string(buf)) // Would print `{"obj":null,"foo":"bar","age":10`, not sure why its missing the closing }
}
```

That way you could unmarshal the JSON to a go struct and do whatever you want with that inside the hook. 
Is this viable? I would gladly make a PR, if it seems that it could work and you could point me why it is missing the closing braket. @rs

**Comment by rs** [comment]
Zerolog builds the json output on the fly with no allocation. What you get here is an incomplete JSON output. You can't change it and expect zerolog to produce a valid JSON afterward.

Additionally, unmarshaling JSON in a hook would just kill performance of the lib.

**Comment by Vanclief** [comment]
Understood, thanks for the clarification.

**Comment by komuw** [comment]
The [proposed](https://github.com/golang/go/issues/56345) structured logging library for Go stdlib(`golang.org/x/exp/slog`) has an interesting method that I think would be useful to emulate in zerolog; https://pkg.go.dev/golang.org/x/exp/slog#Record.Attrs  

maybe;
```go
// Buf calls f on the underlying byte buffer.
func (e *Event) Buf(f func(buf []byte)) {
	f(e.buf)
}
```

But there are still some open questions; should `f` be called in a different goroutine? should `e.buf` be deep copied so that `f` gets its own unique slice? what about allocation?

In all, I'm not sure if it is a good idea; I'm just throwing it out there.

**Comment by iotanbo** [comment]
Same story.
I'm trying to use zerolog.Hook to filter log messages based on their LogLevel and
possibly keys they contain and send those filtered ones to Telegram.
The problem is: I don't see how I can convert the `Event` to JSON. It'd be nice
to have something like `e.ToJSON()`.
I understand that it will degrade performance for those filtered messages because rendering will occur twice, but that overhead is nothing compared to the overhead of Telegram API. 
Currently I can use only `level` and `message` input parameters which is sort of workaround.
