### ISSUE TITLE
The order of the 'time' field is inconsisent between different logging forms

### ISSUE THREAD

**Issue by Muddz** [rs/zerolog#311]
I have three examples of different logging forms where each results in the `time` field being written in a different order.
Is it possible to always have `time` as the first or second field and why is this behaving like this?

```
log.Error().Msg("failed to start server")
//Prints
{"level":"error","time":"1619122881","message":"failed to start server"}
```

```
log.Error().Err(err).Msgf("failed decoding body from POST %s:", "/var/superconfig.yml")
//Prints
 {"level":"error","error":"file already open","time":"1619122881","message":"failed decoding body from POST /var/superconfig.yml:"}
```

```
log.Info().
		Str("Method", "GET").
		Str("Path", "/UserConfig").
		Str("User-Agent", "Windows 10").
		Str("Client", "93.23.42.44").
		Send()
//Prints
{"level":"info","Method":"GET","Path":"/UserConfig","User-Agent":"Windows 10","Client":"93.23.42.44","time":"1619122881"}
```

**Comment by rs** [comment]
The timestamp is part of the context and is written after the fields and before the message. It's consistent. The reason is that zerolog does write the json buffer directly, there is no intermediate form. The context is written by the Msg/Send method, it can't be done before so it's not possible to have it as the first field.

**Comment by phuslu** [comment]
you're not alone, i also suffer this problem so i wrote my own logger then let the time filed always presents and be the first.
