### ISSUE TITLE
Global log level is not respected 

### ISSUE THREAD

**Issue by schmigware** [rs/zerolog#394]
This issue concerns the following logic (log.should): https://github.com/rs/zerolog/blob/3efdd82416f68f3b359032b717160e317c9c2bd5/log.go#L453

```
if lvl < l.level || lvl < GlobalLevel() {
    return false
}
```
Unless I am misunderstanding the intent of the global level functionality, I would expect should() to return **true** for a case when lvl < l.level but >= GlobalLevel. The following comment indicates as much to me:

// SetGlobalLevel sets the global override for log level. If this
// values is raised, all Loggers will use at least this value.

If I'm correct, the following will fix. Please let me know if this is the case and I'll open a PR.

```
	if lvl < l.level && lvl < globalLevel {
		return false
	}
```

**Comment by rs** [comment]
The global level is only used if the logger's level is less strict (lower) than global's. So if you set global level to info and logger's level to error, only errors and higher will be logged.

**Comment by schmigware** [comment]
Many thanks. I'm looking for a logging lib which will allow me reset levels dynamically ala-log4j and had mistakenly understood the global level functionality. Back to the drawing board then! Many thanks @rs

**Comment by bvisness** [comment]
I just got bitten by this, and find it quite counterintuitive. If my global level is set to `WarningLevel`, but I create a new logger with an explicit `DebugLevel`, I expect to see debug stuff, and for the global level to no longer apply. Instead, I _still_ don't see debugs.

I realize this may be difficult with the way the levels are currently defined (where zero is `DebugLevel` instead of, say, `NoLevel`). But I think the current behavior is confusing and undesirable.
