### ISSUE TITLE
pretty print not working

### ISSUE THREAD

**Issue by salman0ansari** [rs/zerolog#485]
![image](https://user-images.githubusercontent.com/30106022/193338742-91d66055-314e-4fd1-8a4d-b3a8f33b9457.png)

![image](https://user-images.githubusercontent.com/30106022/193339084-ba35828f-ca80-49fc-a952-915ee214e40b.png)

![image](https://user-images.githubusercontent.com/30106022/193339166-0f53be1c-a116-41e8-a389-14c715d5e62c.png)

**Comment by pscheid92** [comment]
Hello @salman0ansari 👋 

I'm afraid that this is not due to some error in zerolog, but the Windows Console is not supporting [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code#DOS,_OS/2,_and_Windows).

I haven't used Microsoft Windows for years, so I cannot provide a solution. But the Wikipedia article above mentions using "Windows Terminal" as a solution 🤔 

> [Windows Terminal](https://en.wikipedia.org/wiki/Windows_Terminal), introduced in 2019, supports the sequences by default, and Microsoft intends to replace the Windows Console with Windows Terminal.

**Comment by salman0ansari** [comment]
it worked using this method 
https://github.com/sirupsen/logrus/issues/172#issuecomment-353724264
